repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: name-tests-test
        args: [ --pytest-test-first ]
        exclude: "(^tests/utils|manual/)"
      # doesn't handle requirements divided into groups by comment blocks
#      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ '--config=.flake8' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]

  - repo: local
    hooks:
      - id: tests
        name: Run tests
        entry: .venv/bin/pytest --cov=src --cov=tests --junitxml=test-results/junit.xml -v ./tests
        language: script
        pass_filenames: false
        verbose: true
